### ISSUE TITLE
gulp

### ISSUE THREAD

**Issue by Oliviercreativ** [Scriptura/ScripturaFramework#1]
Bonjour,
J'ai cloné le **reposity**, ensuite j'ai fait " **npm install** " pour installer les indépendances.
Et quand j'ai Gulp dans le dossier " **Root** ", j'ai eu cette erreur :
`module.js:339
    throw err;
    ^

Error: Cannot find module 'gulp-sync'
.....` 
Du coup j'ai fait **npm install gulp-sync** ect pour toutes les erreurs. Je suppose qu'on peut faire une install commune. Une issue svp ?

Merci

Ps: je n'ai pas mis les sudo mais je les ai mis dans toutes les install,  je suis sous mac.

**Comment by Scriptura** [comment]
Bonsoir,

Je me suis penché sur votre problème :
1/ il y avait un bug de mon côté : mon fichier `package.json` n'était pas complet, vous ne risquiez donc pas d'arriver à vos fins... Désolé. J'ai corrigé le problème, désormais ça fonctionne, il vous faudra donc forker à nouveau le repository si vous souhaitez persévérer.
2/ Évitez de faire une installation globale pour les plugins Gulp, ce qui évitera que ces plugins puissent entrer en conflit avec d'autres projets qui utiliseront ces mêmes plugins, mais dans des versions antérieures ou postérieures. Préférez une installation de dev en ajoutant `--save-dev` à vos commandes. Exemple :
`$ sudo npm install --save-dev gulp-sync`

Je n'ai mis qu'une seule page de démarrage pour mon projet car certaines personnes m'ont fait remarquer que le fichier de démonstration dans son ensemble était trop lourd à télécharger. Si cependant ces pages vous intéressent, vous pouvez les trouver ici : [https://github.com/Scriptura/scriptura.github.io](scriptura.github.io)

Cordialement

**Comment by Oliviercreativ** [comment]
Super merci pour la réponse ;)
J'ai réussi à l'installer et à m'en servir mais je vais tout de même faire un Fork.

Cordialement

**Comment by Scriptura** [comment]
Et n'oubliez pas que le projet est en version beta ! C'est pour cela que je ne l'ai pas encore versionné.
